### ISSUE TITLE
v2.6: many app crashes on loading map archives / start unzipping them

### ISSUE THREAD

**Issue by stephan75** [junjunguo/PocketMaps#102]
On my android 5.1 device I updated to app version 2.6, and later even complete reinstall, but I keep on getting crashes when downloadibg map files or when the app wants to start unzipping the downloaded map files.

Crash logs should be sent via android crash report feature that developers can see in their playstore console.

Maybe due to limites write access to sd card or internal memory? What about a teating feature on app start whether teh app has write acces to the medium where mapfiles are to be stored?

**Comment by Starcommander** [comment]
Hello Stephan!
Yes, I can see the crash report, thanks.
Seems, it has to do with IO access, as you supposed.
But what is a teating feature?

An other possibility is, that the maps folder is missing.
Could be very helpful, when you can navigate to the pocketmaps directory via a file browser.
There should be a directory like pocketmaps/maps/country-gh/
..... where country is the map you downloaded. Example: asia_bhutan-gh
Here you can try to create the directory and restart download.

Did you also try to change the maps directory?
Maybe your sd-card is corrupted?
Did the download finish? And can you see the file in a file browser?
Did PocketMaps ever work for you in an older Version?

**Comment by stephan75** [comment]
Ohh, typo: testing feature was meant ...

And app version 2.2 was working ... Trouble started with 2.5

Will try some things with map file path in the next days.

**Comment by stephan75** [comment]
I can choose three map store paths:
internal memory -> android/media
internal memory -> downloads
sd-card -> android/media

When choosing sd-card, the map download will NOT start at all.

and saving map downloads on internal memory results all the times in the mentioned errors, see log files.

Thus I think: the app needs testing features after users choice of a map download path whether that pass gives write access etc to the app.

**Comment by Starcommander** [comment]
Please try - as suggested - to create the folder, and download again!
This is necessary to find out, whether the missing folder is the issue.

**Comment by stephan75** [comment]
Ohh, indeed: Your hint was correct about the missing folder:

The maps folder was empty,
so I created a new folder via TotalCommander and named it europe_germany_hamburg-gh ...

and pocketmaps does not crash anymore so far.
I was even able to see an unzipping progress message, and finally, the map was shown!

So the missing folder really seems to be the issue.
