### ISSUE TITLE
Cannot download maps if external storage is selected as map location

### ISSUE THREAD

**Issue by githtz** [junjunguo/PocketMaps#104]
App-Version: pocketmaps@2.7
Source: F-Droid
Android-Version: 8.1.0

Prerequisites:
I've set the map download path to _/storage/_**sd-card-id**_/Android/media/com.junjunguo.pocketmaps_ via the in-build download location picker.

Description of the bug:
I try to download a map via the in-built map-brwoser. I press the download button. The downloading icon appears in the status bar but the download fails instantly without further notice.

**Comment by Starcommander** [comment]
Thanks for your report.
Are you able to download any maps on other storage locations?
Is it possible, that you have mounted the sd-card as read-only?
Maybe you can send me a bug-report from developer-settings of android after reproducing the issue?
This could help me to find the reason for this issue.
My email is soundmodul@gmx.at

**Comment by githtz** [comment]
@Starcommander 
Sorry, just realized I forgot to answer. I was able to download the maps to my internal storage without any problem. The sd-card should not be mounted as read only since I've got other apps (e.g. NextCloud) that store their data there.
I'm not sure how to send that bug report, but I guess the problem is one of my device, since I was able to get a log via logcat from the DonwloadManager. I'll add the exact excpetion, but I guess this problem is not related to this app.

**Comment by letkan** [comment]
Same problem on a Redmi note 3SD with AEX rom. if you didn't figure out yet this issue I'll try to get some logcat. I just discovered this app and am evaluating it, so far so good. :)

**Comment by Starcommander** [comment]
I did not figure out this yet, nor find the reason for this behaviour.
So additional logcat output can be very helpful.
Thanks in advance.

**Comment by letkan** [comment]
I'm pasting the relevant part:

> 11-27 01:45:08.998  4945  4945 I com.junjunguo.pocketmaps.activities.DownloadMapActivity: Register receiver for map: europe_romania
11-27 01:45:09.011  4369  5356 D DownloadManager: [22] Starting
11-27 01:45:09.031  4369  5356 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-27 01:45:09.038   459  4023 D audio_hw_primary: start_output_stream: exit
11-27 01:45:09.325  4369  5356 E DownloadManager: [22] Failed: java.lang.IllegalArgumentException: Invalid UUID string: 7BD0-6B26
11-27 01:45:09.325  4369  5356 E DownloadManager: java.lang.IllegalArgumentException: Invalid UUID string: 7BD0-6B26
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at java.util.UUID.fromString(UUID.java:194)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at android.os.storage.StorageManager.convert(StorageManager.java:1952)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at android.os.storage.StorageManager.getUuidForPath(StorageManager.java:756)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at android.os.storage.StorageManager.isAllocationSupported(StorageManager.java:780)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at com.android.providers.downloads.DownloadThread.transferData(DownloadThread.java:585)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at com.android.providers.downloads.DownloadThread.executeDownload(DownloadThread.java:470)
11-27 01:45:09.325  4369  5356 E DownloadManager: 	at com.android.providers.downloads.DownloadThread.run(DownloadThread.java:312)
11-27 01:45:09.326  4369  5356 D DownloadManager: [22] Finished with status UNKNOWN_ERROR
11-27 01:45:09.395  4945  4945 I com.junjunguo.pocketmaps.activities.DownloadMapActivity: Error downloading map: europe_romania
11-27 01:45:09.395  4945  4945 I com.junjunguo.pocketmaps.activities.DownloadMapActivity: Clearing dl file for map: europe_romania

**Comment by githtz** [comment]
This could be a problem with android Oreo and above; found [this](https://stackoverflow.com/questions/48589109/invalid-uuid-of-storage-gained-from-android-storagemanager) on StackOverflow.

**Comment by Starcommander** [comment]
Is 8.1.0 the only affected version of android?
Did anyone try this on an other similar version?

**Comment by Starcommander** [comment]
I tried it with the following device today:

> Galaxy A5 (2017)
> Android Version 8.0.0
> Samsung Experience Version 9.0

Not reproducible with this device, download works as expected.

**Comment by githtz** [comment]
I've tried this with Android 7.1.2 (LineageOS 14.1) and could also not reproduce this behavior.

**Comment by rbertoche** [comment]
I'm running LineageOS 16.0 on a Xperia SP and I have the same issue. I'll get you the logs as soon as it charges enough. After copying the data to the SD card everything works fine.

**Comment by rbertoche** [comment]
I get another kind of error without a traceback. Its a permission denied
`01-26 02:55:33.121 16419 18590 D DownloadManager: [121] Starting
01-26 02:55:33.172 16419 18590 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-26 02:55:33.182 16419 18590 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-26 02:55:33.229 16497 16497 I com.junjunguo.pocketmaps.activities.DownloadMapActivity: Register receiver for map: africa_benin
01-26 02:55:34.830   333   333 E WifiHAL : wifi_get_link_stats: requestResponse Error:-3
01-26 02:55:34.834  6350  6491 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
01-26 02:55:35.155 16419 18590 W DownloadManager: [121] Stop requested with status FILE_ERROR: Failed to generate filename: java.io.IOException: Permission denied
01-26 02:55:35.159 16419 18590 D DownloadManager: [121] Finished with status WAITING_TO_RETRY
`

**Comment by Starcommander** [comment]
@rbertoche Seems, that newest versions of android may also have problems with download-manager.
Downloading to internal storage works for you on pocketmaps?
Maybe you can also show the access-rights of the folder com.junjunguo.pocketmaps
(using ls -l for example)

**Comment by Starcommander** [comment]
I tried it with Android_X86 8.1.0 and there is also an error downloading maps to external storage.
(Of curse, the map-view itself can not work on x86 processor)
Maybe I can find out more ...

**Comment by dorothymercado** [comment]
I have the same problem on lineage OS/Android pie.

**Comment by Starcommander** [comment]
a40b42aa7c0003cc18c5961233a18e839f7ceb5e

**Comment by Starcommander** [comment]
The only way to work around this bug was to temporary use internal storage for downloading.

**Comment by Starcommander** [comment]
85e681e2b8dbca97ebe35d8f0be19c7e3524083c
Using modified (local) DownloadDirectory in any case for android-orion.
