### ISSUE TITLE
Start up on network location

### ISSUE THREAD

**Issue by letkan** [junjunguo/PocketMaps#105]
Whenever I launch the app and I'm on network location only (android 8) the screen flickers for a second and I'm passed to location settings. If I just hit the back button I'm returned to the main layout of the app. This doesn't happen if the phone is set to high accuracy but it does happen if I'm set on gps only and am indoors. I guess it has to do with checking for access to fine location vs. coarse location. I don't know if it matters, I don't use gapps but the NetworkLocation part of microG.

**Comment by Starcommander** [comment]
PocketMaps is showing the GPS setting, when entering the map.
This is useful, when GPS is disabled (or network only).
The user can decide to enable GPS, or just to go back.

Is there something wrong with this behaviour?
Maybe I understood something wrong?

**Comment by letkan** [comment]
"Is there something wrong with this behaviour?" Wrong is too strong a word, maybe limiting. In populated areas (city) I tend to rely on network location because it is accurate and fast unlike gps which works better in open spaces. I guess my main point is that the app behaves as if only gps is the means to establish a location and not network.
Nevertheless, I really like your app, it's good clean work.

**Comment by Starcommander** [comment]
Maybe showing an options-dialog instead redirecting to gps settings may be an improvement.
Message: GPS is turned off!
Options: [back] or [gps settings]

**Comment by letkan** [comment]
> Maybe showing an options-dialog instead redirecting to gps settings may be an improvement.
> Message: GPS is turned off!
> Options: [back] or [gps settings]

Sounds good, thanks. Have a good year.

**Comment by Starcommander** [comment]
Fixed in V2.8
