### ISSUE TITLE
Missing sub regions

### ISSUE THREAD

**Issue by nowthen** [junjunguo/PocketMaps#111]
When I run script ./import_maps_paul.sh -i (interactive option) I cannot find sub regions of Great Britain i.e. England, Scotland, Wales and the sub regions of England e.g. Bedfordshire etc. There are sub regions for France, Germany etc., but not GB. The special sub regions are also missing e.g. British Isles.  These maps do exist, but the script does not find them.

Can these sub regions be added?

**Comment by Starcommander** [comment]
Hello @nowthen 
You have to add (or modify) a line at the end of the script.
There are the lines **`import_continent ******`**
In this case you need:
**`import_continent europe/great-britain`**

**Comment by nowthen** [comment]
Hello@Starcommander
Yes. I had just figured that out.

I added after line 468:
**import_continent europe/great-britain**
This find sub regions England, Scotland, and Wales.

I also added:
**import_continent europe/great-britain/england**
to get the sub regions of England, but that does not work. 

The script tries to download (for example):
**http://download.geofabrik.de/europe/england/herefordshire-latest.osm.pbf**
when it needs to find:
**http://download.geofabrik.de/europe/great-britain/england/herefordshire-latest.osm.pbf**

The script requires some changes to fix this. I'm a user, not a programmer/developer so this is beyond my know how.

**Comment by Starcommander** [comment]
Fixed, but not tested.
