### ISSUE TITLE
Zip Path Traversal

### ISSUE THREAD

**Issue by akyzi007** [junjunguo/PocketMaps#112]
Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.
Vulnerable locations:
com.graphhopper.util.Unzipper.unzip

**Comment by Starcommander** [comment]
Hello @akyzi007 !
Thanks for your message!
Currently I have no clue, howto solve this issue.
Do you have a link to "this Google Help Center article"?

Best regards.

**Comment by akyzi007** [comment]
Hello, 
Here is the link. Please have a look. 
https://support.google.com/faqs/answer/7496913?hl=en

Thank you,
Best Regards

**Comment by Allay054** [comment]
Hi you are doing best ,currently i'm facing this issue, have you sort out this issue "Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.
Vulnerable locations:
com.graphhopper.util.Unzipper.unzip
"

Thanks

**Comment by Starcommander** [comment]
@Allay054 
Currently not.
I think, I will fix it within the next few weeks.
I did not have time yet.

**Comment by Allay054** [comment]
Ok thanks for reply and please let me know when you fix this

**Comment by Starcommander** [comment]
@Allay054 
I have verified the issue.
It does not affect the source code of pocketmaps, but the used library "graphhopper"
Here you can see the fix:
https://github.com/graphhopper/graphhopper/commit/b2a5574b02288b7cc1144c7cadfc67804190db30

My part is now to include a fixed version of graphhopper.

**Comment by Allay054** [comment]
Thanks for giving me your feedback it help me a lot
Thanks again

**Comment by akyzi007** [comment]
Hello,
I have solved this problem. Let me know if you still need help. I can guide
you.
Thank you

Best Regards

**Comment by Allay054** [comment]
Thanks have you updated project on github?

**Comment by akyzi007** [comment]
Yes, you can use this fixed version of Graphhopper by including this dependency in build.gradle (app module)
implementation(group: 'com.github.bilal3387.graphhopper', name: 'graphhopper-core', version: '0.13.0-fixed') {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'org.openstreetmap.osmosis', module: 'osmosis-osm-binary'
        exclude group: 'org.apache.xmlgraphics', module: 'xmlgraphics-commons'
    }

and in build.gradle (project module) repositories, use
        maven { url "https://jitpack.io" }

**Comment by Starcommander** [comment]
Switched to new version 0.13.0 of graphhopper.
Should be resolved in next release of pocketmaps.
Thanks for all your help!
