### ISSUE TITLE
Crash after revocation of permission

### ISSUE THREAD

**Issue by Thunder7Lightening** [junjunguo/PocketMaps#115]
I was in this page, top left picture.
Then I went back to desktop screen and using adb to revoke storage permission, 
the screen showed like the top right picture.
When I pressed the Allow button for Location Permission, 
PocketMaps went crash.

![Screenshot_20190724-211910_Package installer](https://user-images.githubusercontent.com/31926495/61796885-e1ca5700-ae58-11e9-9f04-5838af68d36f.jpg) ![Screenshot_20190724-211915_Package installer](https://user-images.githubusercontent.com/31926495/61796888-e3941a80-ae58-11e9-9e5d-e87b28784115.jpg) ![Screenshot_20190724-211931_PocketMaps](https://user-images.githubusercontent.com/31926495/61796890-e4c54780-ae58-11e9-8d09-87229c58359b.jpg)

**Comment by Starcommander** [comment]
Hello @Thunder7Lightening 
Thanks for your message.
What happens, after restarting the app again?
And what exactliy is the adb command, that you have accessed?
Did you allow File-Access on Pocketmaps-UI and then revoked File-Access via adb?
Maybe you can also post a logcat output after crash via adb?

Thanks for your effort.

**Comment by Starcommander** [comment]
I can reproduce this issue, just deny already granted access to files via app-settings.
This is a very unlikely bug, and a restart of the app is possible.
Nevertheless solved for next version. (3.0?)
