### ISSUE TITLE
Program type already present: com.caverock.androidsvg.BuildConfig

### ISSUE THREAD

**Issue by zainriaz** [junjunguo/PocketMaps#117]

**Comment by Starcommander** [comment]
Hello @zainriaz !
Can you please write down a description, what is the reason for this issue?!

Thanks in advance

**Comment by zainriaz** [comment]
Using this  "implementation 'com.caverock:androidsvg-aar:1.4' "  the error mentioned above occurs, during  project build.

**Comment by Starcommander** [comment]
Hello @zainriaz !
Thanks for the report, but I am not able to reproduce that error.
I also tried to make a fresh build inside a docker, but also this builds without any problem.

Can you provide a complete console-output inclusive executed command?
Did you use **./gradlew build** for building the project?
And what is your OS?

**Comment by letkan** [comment]
In Android Studio I've had the same problem. I fixed it like this:
- Commented out implementation 'com.caverock:androidsvg-aar:1.4' in build.gradle (app)
- Added android.useAndroidX=true, android.enableJetifier=true.
Also used classpath 'com.android.tools.build:gradle:3.5.2' in build.gradle (project) if it's of any relevance.
Platform Linux Manjaro.
