### ISSUE TITLE
No more map of Italy after latest update

### ISSUE THREAD

**Issue by surferjoeit** [junjunguo/PocketMaps#119]
Hello,
i recently updated to 3.0 version via F-Droid and since then i can't open downloaded Italy maps. A message says that i have to update them but there is no map of Italy available anymore.
Thanks

**Comment by Starcommander** [comment]
Hello @surferjoeit !
Thanks for your message.

Some maps are not finished yet.
So I will still need some days.

Best regards,
Paul

**Comment by Starcommander** [comment]
Started Italy map today.
Should be finished in some hours.

**Comment by surferjoeit** [comment]
Many thanks!
