### ISSUE TITLE
Downloaded maps are not compatible with application version

### ISSUE THREAD

**Issue by treqzct** [junjunguo/PocketMaps#120]
Problem: the app says "The maps are not compatible with this version! Please update maps!" or something like that

What I did:
1. Downloaded from f-droid and installed PocketMaps version 3.0
2. Opened the PocketMaps app
3. Selected and downloaded a map file from inside the app
4. The app shows the downloaded map but when I click on it it says "The maps are not compatible with this version! Please update maps!" or something like that

Any ideas? Thanks

**Comment by Starcommander** [comment]
Hello @treqzct !

Did you try different maps?
Which map did you already try to download?

Best regards

**Comment by treqzct** [comment]
I tried only one map: New York, USA.

**Comment by Starcommander** [comment]
I was able to load the map without any issues.
Please try to delete (swipe out) the map and re-download again.
Does this help?

**Comment by treqzct** [comment]
Maybe we can do it in a different way: If you tell me the name of the file I need to verify and its location I will tell you what its md5sum hash is and then you can compare it to your own hash perhaps? Thanks

**Comment by Starcommander** [comment]
Basically it has to do with the version.txt file.
The file is created after downloading and unzipping of the maps.
Maybe there was a problem, with unzipping, so the version file was not created.
Did you kill the app after downloading?
The content of the version.txt file:
0.13.0_0

But why not downloading the map again?
Would be interesting whether the error occurs again or it was a sporadic problem.

Here the list of md5sums of folder **north-america_us_new-york-gh** :
5788dd6f705c108b36b72cea29434c65  ./city_nodes.txt
3e5d94cd21532f888d67f0176506556c  ./edges
39176964362605cc0e0249db66d24c9a  ./geometry
e3539c9408787f432952445b61939440  ./location_index
32f56cf7f965076864ddf7d05266650a  ./names
74acb724365089451e8782f170b66ab0  ./nodes
33ef865adb08e4d0e185438073a035f3  ./nodes_ch_fastest_bike_node
2736f2065bb3d3734c40c4f9ac968cf7  ./nodes_ch_fastest_car_node
ba74d08ca07c08b6af265af824cbee27  ./nodes_ch_fastest_foot_node
5493d850c41d0f67f8dd8ab9f9235b0a  ./nodes_ch_shortest_bike_node
f5b5cb6298ba8cc175ece3ff0d3cbb09  ./nodes_ch_shortest_car_node
2808e0cbbc83c4f76ce6b78e7af03e33  ./nodes_ch_shortest_foot_node
ec218ff73c1999fbb8c0c3cdb35fb5ff  ./north-america_us_new-york.map
2356c3606bf96c3b3a2f6312fd2ed2d6  ./properties
d533e8078e582d79475822b21f66ef01  ./shortcuts_fastest_bike_node
32d29eda884e083e63d2c78ddbe0de65  ./shortcuts_fastest_car_node
982434aee883973bf31fd91eb2e90c05  ./shortcuts_fastest_foot_node
d9ed7d338760b60956e1acd692435b21  ./shortcuts_shortest_bike_node
e12505164a5dbdc32a17883e3dde3781  ./shortcuts_shortest_car_node
fa9d9d2b4e010aeb55afffc85f3a53f5  ./shortcuts_shortest_foot_node
50a019651d1d2197e8780cb5062b0289  ./version.txt

**Comment by treqzct** [comment]
> Maybe there was a problem, with unzipping, so the version file was not created.
> Did you kill the app after downloading?

Perhaps. It was missing the version.txt file. It works now. Thanks.

**Comment by innodeltech** [comment]
how to generate nodes_ch_fastest_bike_node file?

**Comment by Starcommander** [comment]
All is generated with the script mapGenerator/import_maps_paul.sh
