### ISSUE TITLE
Search engine default, offline search, etc

### ISSUE THREAD

**Issue by treqzct** [junjunguo/PocketMaps#121]
Tried PocketMaps (PM) for a couple of hours, here are some impressions. Feel free to close this ticket if you don't find any of the following of use:

Generally, I like the way PM looks, it seems a bit snappier than navit (though in my case navit loads a map that's about five times larger than what I used for test purposes with PM).

Some issues:

1. Search engine: A bit annoying that PM does not remember the last used search engine and does not allow to set the default search engine.

2. Offline Search: I couldn't find anything using the PM offline search mode, even the places I know well. For example, try to find, say, 655 Park Avenue, New York, NY. PM shows the wrong place (at least in the 655 Park Avenue case it shows the right city in the search results, in some cases it does not do even that).
Maybe you should consider implementing Offline search the way navit does it: Enter a town/city name, select town from the list of matching towns, enter the street name, select the street from the matching list, enter house number, etc.

3. Offline Search results presentation: It needs to be improved, I think. The map name (something like NORTH-AMERICA_US_NEW-YORK ) is shown in a big font and takes a lot of space while the name of the actual town is shown in a tiny, barely readable font. It would've been a lot better if it would show something like Town Name, State/Province, Country (for example , Queens, NY, USA or Brooklyn, New York, USA, etc).

4. No "Avoid tolls" car mode?

5. Any way to see (and filter) Points of interest near a certain location?

6. Adding a new bookmark is not intuitive, it takes several steps and a bit more clicks than I would have liked. Someone suggested creating a new bookmark on long press, maybe this idea is worth looking into. Also, it would be nice if PM prepopulated the title with the address, for example "123 Main St, Sometown, State, Country".

HTH,

**Comment by Starcommander** [comment]
Hello @treqzct !
Thanks for sharing your impressions of pocketmaps.

Some first thoughts ...
1. That is a good Idea. Also it is possibly helpful to store the last search-text inputs.
2+3. Offline search is still very limited. Maybe I can improve that like your suggestion.
4. Obviously this is not implemented in open source version of Graphhopper
https://github.com/graphhopper/graphhopper/issues/643

Best regards,
Paul

**Comment by Starcommander** [comment]
Hello @treqzct 

1,2,3) I have improved offline-search and search-results.
4) Seems not possible as already explained.
5) Basically you can see the POI-Icons on the map.
There is no easy way to get a list, or filter them.
6) I will implement a different way for simplified set a Favourite/Bookmark.
(I do not like the idea of long-press-on-map).

Best regards,
Paul
