### ISSUE TITLE
Error decompressing map

### ISSUE THREAD

**Issue by letkan** [junjunguo/PocketMaps#126]
This is weird, last time I complained about not being able to install a local map it was about the sd card, now I'm getting this error  on built-in storage but I have no problem doing it on sd card. SD card works fine for me, just saying.

Unrelated, the app downloaded from f-droid wouldn't run, I built myself v 3.1 and it worked fine.

Rom AOSiP Android 10.

**Comment by Starcommander** [comment]
Hello @letkan 
Thanks for opening an issue.

The message is: 

> Error unpacking map: mapname

 right?
And what do you mean by

> the app downloaded from f-droid wouldn't run

Can you please explain this in more detail?
May be you can also create a logcat output via adb?
This would help me a lot to find the reason for this issue!

Best regards, Paul

**Comment by letkan** [comment]
Actually I took a logcat, see if it helps:
[logcat.zip](https://github.com/junjunguo/PocketMaps/files/4037193/logcat.zip)

As for explanations, I just downloaded the app from f-droid, installed it and every time I tried to run it it would force close.

Also, check my comment to closed issue [#117](https://github.com/junjunguo/PocketMaps/issues/117), no idea if it's related.

**Comment by Starcommander** [comment]
Oh yes, there are many of hints!

```
01-08 19:04:02.252 11553 11553 E PackageManagerCompat: Could not set installer package name for com.junjunguo.pocketmaps
01-08 19:04:02.252 11553 11553 E PackageManagerCompat: java.lang.SecurityException: Caller does not have same cert as old installer package com.android.packageinstaller
```
Seems, you tried to install the app from f-droid where the app was already installed with different cert? Possible? You have to clear the app first in such a case for security reasons.

```
01-08 19:04:32.468 14102 14102 I com.junjunguo.pocketmaps.activities.MainActivity: Warning: mapsFolder does not exist!
01-08 19:04:32.471 14102 14102 D AndroidRuntime: Shutting down VM
java.lang.RuntimeException: Unable to resume activity {com.junjunguo.pocketmaps/com.junjunguo.pocketmaps.activities.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
```
Seems the app does not have access-rights to the selected maps-directory for any reason.
I will at least catch that exception.

Best regards,
Paul

**Comment by letkan** [comment]
> Seems, you tried to install the app from f-droid where the app was already installed with different cert? Possible? You have to clear the app first in such a case for security reasons.

You are right. I don't know what I did, sorry for the false alarm.

**Comment by Starcommander** [comment]
No problem!
Maybe you can try to rebuild the app with this small fix.
If you have any issue again it is most helpful to create a logcat output directly afterwards.

Thanks.
Best regards, Paul.

**Comment by letkan** [comment]
> Maybe you can try to rebuild the app with this small fix.

I will, thanks.

**Comment by Starcommander** [comment]
@letkan I will close this issue now.
Please do not hesitate to open the issue again, or create a new one.

Best regards,
Paul
