### ISSUE TITLE
Selecct map automatically menu is broken

### ISSUE THREAD

**Issue by keddad** [junjunguo/PocketMaps#127]
![image](https://user-images.githubusercontent.com/34062895/72165246-08f0f280-33bf-11ea-81e5-b88047234677.png)
I guess the image is explaining everything. Version 3.1 from F-Droid.

**Comment by Starcommander** [comment]
Hello @keddad !

Thanks for opening this issue.
But no, it does not explain any fault.
Selecting the map automatically does work on my device in 3.1

Howto test:
1) Open the menu as on your picture, select checkbox, OK.
2) Select a map, that should be selected everytime automatically.
3) Close the app. (back or home button)
4) Kill the app, or wait a long time until the app is cleared by the system.
5) Start the app again --> This will open the selected map again.

Maybe we should add an explanation-text to the checkbox to prevent misunderstanding.
Best regards
Paul

**Comment by keddad** [comment]
> Hello @keddad !
> 
> Thanks for opening this issue.
> But no, it does not explain any fault.
> Selecting the map automatically does work on my device in 3.1
> 
> Howto test:
> 
>     1. Open the menu as on your picture, select checkbox, OK.
> 
>     2. Select a map, that should be selected everytime automatically.
> 
>     3. Close the app. (back or home button)
> 
>     4. Kill the app, or wait a long time until the app is cleared by the system.
> 
>     5. Start the app again --> This will open the selected map again.
> 
> 
> Maybe we should add an explanation-text to the checkbox to prevent misunderstanding.
> Best regards
> Paul
Sorry, I didn't really get that this is intended behavior. Adding some explanation might be a great idea!

**Comment by keddad** [comment]
> Hello @keddad !
> 
> Thanks for opening this issue.
> But no, it does not explain any fault.
> Selecting the map automatically does work on my device in 3.1
> 
> Howto test:
> 
>     1. Open the menu as on your picture, select checkbox, OK.
> 
>     2. Select a map, that should be selected everytime automatically.
> 
>     3. Close the app. (back or home button)
> 
>     4. Kill the app, or wait a long time until the app is cleared by the system.
> 
>     5. Start the app again --> This will open the selected map again.
> 
> 
> Maybe we should add an explanation-text to the checkbox to prevent misunderstanding.
> Best regards
> Paul

Sorry, I didn't get that this is intended behavior. Adding some explanation might be a great idea.

**Comment by Starcommander** [comment]
Done.
