### ISSUE TITLE
Missing maps

### ISSUE THREAD

**Issue by Starcommander** [junjunguo/PocketMaps#135]
Possibly there are some maps missing.
Examples:
- Solomon Islands (Australia)
- Colombia (South-America)
Other maps?

**Comment by JartThrower** [comment]
I can confirm the map for Colombia is missing. Here is a working one http://www.mediafire.com/file/j7jaqhcr60a5qc8/south-america_colombia.ghz/file

**Comment by Starcommander** [comment]
Seems all maps are uploaded now.
