### ISSUE TITLE
[BUG] Unable to find maps folder after reinstall on sdcard

### ISSUE THREAD

**Issue by 0xlne** [junjunguo/PocketMaps#141]
I made a backup of the app folder, originally /sdcard/Android/media?|data/com.junjunguo.maps & had to do a factory reset of my phone.
It's a 2.3Gb folder which I didn't want to re-download each time I reinstalled the app.
On reinstalling PocketMaps, I moved the folder to one of the recognized locations in the app when trying to switch map folders:
/storage/SERIAL_OF_MY_SD/Android/media/com.junjunguo.maps & restarted the app.
Access to storage has of course been provided to the app, but it's not able to find the maps.

Moving the backed up folder to /sdcard/Android/data on the internal storage works fine though.
As this is on Android 10, PocketMaps might probably be better using SAF instead?

**Comment by Starcommander** [comment]
Hello @0xlne !
Thanks for the report.
Did you try to switch to external disk and download a (small) map?
Does this work?

**Comment by Starcommander** [comment]
@0xlne 
Did you try as suggested?
Would be interesting whether pocketmaps is able to write to this directory.
Just download any little map there.

**Comment by Starcommander** [comment]
No response, closing now.
