### ISSUE TITLE
Crash when touching

### ISSUE THREAD

**Issue by kenneth-Q** [junjunguo/PocketMaps#146]
Since MapsWithMe is[ using OpenStreetMap data illegally](https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/MAPS.ME/MAPS.ME.md) and Osmdroid both used NonFreeAssets, NonFreeNet. So I had to try Pocket maps and fees it is very well. Thanks for your job.

But I get a crash when I click into china's map. I observe that
`an error happened while creating graph:Couldn't map buffer 12 of 137 for shortcuts_fastest_foot_node at position 12583012 for 143654812 bytes with offset 100, new fileLength:143655012`

On the other hand, I find it missing fonts. I think it may cause a crash. Like
![Pocketmaps_screenshort](https://user-images.githubusercontent.com/11911577/81399768-32980b80-915e-11ea-9da6-60e5704ad08b.png)

Last, I have a wish. It could be a good idea to add a function is that we can click a site to show any information (such as coordinates) and add to favorites.

Regards
Kenneth

**Comment by Starcommander** [comment]
Hello @kenneth-Q 
Thanks for your report.
What is your Pocketmaps-version?
Also phone and android version could be helpful.

1) I am not able to reproduce the crash on my phone.
  What exactly are you doing with "click into china's map"?
  And what exactly does happen afterwards?
  And do you have a possibility to create a verbose logcat output?
2) Also regarding Fonts issue my phone seems not affected.
  I have to investigate, where fonts are used in vtm, maybe there is something missing.
  Maybe you can try to test this also on a different mobile phone?
3) You can select the star-button on the border, and select the rect-button there.
  This will allow to select a location, and adds it as a favorite.

Best regards, Paul

**Comment by kenneth-Q** [comment]
Hi @Starcommander 
Sorry for my late response.
I found something before I write this comment.

1. I found that the pocketmaps can run at android 7 and have no crash issue. But at my phone with android 5.0 is not. My phone is Samsung note 3. Also, I had tried to make it run on Samsung note 2 with android 4.4. Unfortunately, it doesn't work with same issue.

2. About font, my two phones (android 5.0 & android 4.4) are same problem. But on android 7, it works fine.

3. Maybe some people have Obsessive–compulsive disorder or some people like to fully select target of position. Also, I like to get the building or point of position and if I want, I can copy the full name of building. That's especially convenient.

The phone with Android 7 is borrow from my relatives. I can't get a new phone. : /. Also, thank you for your kindly response. :)

Regards
Kenneth

**Comment by Starcommander** [comment]
@kenneth-Q 
Thanks for all your testing.

I dont know, whether you are familiar with adb (android debug bridge).
But if you can create a logcat output **after the crash**, then there is a good chance to find the reason for this crash, and fixing it.
https://www.androidauthority.com/about-android-debug-bridge-adb-21510/
Helpful for us is the output of: adb logcat

Is this possible for you?
Otherwise I have to investigate the issue, and try it with a simulator.

Thanks in advance,
Best regards,
Paul

**Comment by kenneth-Q** [comment]
Hi Paul
happy to see you again.

I found the google play could send the crash log to developer. Will it work for you?

Regards
Kenneth

**Comment by Starcommander** [comment]
Yes, maybe this will also do what i need.

**Comment by Starcommander** [comment]
@kenneth-Q 
Did you already send such a crash log?

**Comment by kenneth-Q** [comment]
> I found the Google play version could send the crash log to developer.
I may wrong. Sorry.
I get logcat log here. 
[pocketmaps.log](https://github.com/junjunguo/PocketMaps/files/4613313/pocketmaps.log)
Thank you for your job.

**Comment by kenneth-Q** [comment]
> E/gralloc ( 6162): Failed to create UMP handle
W/GraphicBufferMapper( 6162): registerBuffer(0x629acde8) failed -22 (Invalid argument)
E/GraphicBuffer( 6162): unflatten: registerBuffer failed: Invalid argument (-22)
E/[EGL-ERROR]( 6162): mali_surface* __egl_platform_create_surface_from_native_buffer(android_native_buffer_t*, egl_surface*, mali_base_ctx_handle):701: failed to map physical memory (0x0 + 0)
F/libc    ( 6162): Fatal signal 6 (SIGABRT) at 0x00001812 (code=-6), thread 6162 (nguo.pocketmaps)

I think it is the problem. (I don't know more about android). :)
I hope it will be fix.(faster. I use to take gps record - gpx). ^.^
Thank you for your job again. I really need osm map.

**Comment by Starcommander** [comment]
@kenneth-Q 
Thanks for the further information.
But this task seems not easy to handle.
Did you also try different maps, and do you have the same issue there?

**Comment by kenneth-Q** [comment]
I've tried [maps(Fork of MapsWithMe)](https://gitlab.com/axet/omim) and MapsWithMe. They are work fine on my phone.

**Comment by Starcommander** [comment]
@kenneth-Q What i mean: did you try to download different maps **with pocketmaps**, and do they have the same issue.
For example some small maps like Malta (26Mb)
Because maybe it has to do with memory limit.
Thanks in advance

**Comment by kenneth-Q** [comment]
> @kenneth-Q What i mean: did you try to download different maps **with pocketmaps**, and do they have the same issue.
> For example some small maps like Malta (26Mb)
> Because maybe it has to do with memory limit.
> Thanks in advance

You are right. I had tried Norway, and that work fine.

**Comment by kenneth-Q** [comment]
I tested the Indonesia map and it crashed too.

**Comment by Starcommander** [comment]
@kenneth-Q 
At the first glance i would say it has to do with map size.
I fear your phone does not have enough memory (ram).
Maybe you can try more small maps and share your results.
As a workaround we can split the map of china, but this is some work.

**Comment by kenneth-Q** [comment]
Sorry for the late response. I think a lot of countries should be split for a small size. That may have a lot of work to do. So, thank you for your work. That works fine on my phone with small maps.

**Comment by kenneth-Q** [comment]
Hi @Starcommander
Sill going on?

**Comment by Starcommander** [comment]
@kenneth-Q 
I have created a china-latest-west.
Can you try it?

**Comment by kenneth-Q** [comment]
I have tried. That is work for me.
Is the china-latest-west for test?

**Comment by Starcommander** [comment]
@kenneth-Q 
Basically I will keep the map, but rename it to china-west.
So you should delete and re-download it later, because of yearly updates.
Next time I create china-center and china-east.
Hope that will help.

**Comment by Starcommander** [comment]
I renamed the map now to china-west.
Currently available: china-west and china-center.
Today I will finish china-east.
