### ISSUE TITLE
My app keeps on crashing

### ISSUE THREAD

**Issue by mobbydixk** [junjunguo/PocketMaps#147]
As soon as i try to run it it crashes. 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.junjunguo.pocketmaps/com.junjunguo.pocketmaps.activities.MainActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by Starcommander** [comment]
@mobbydixk What is the version of pocketmaps app, that you try to start.
Where did you install it. (fdroid/google_play_store/apk)
What is your Android version?
And do you have some more lines of the error output?
Thanks in advance.

**Comment by Starcommander** [comment]
@mobbydixk Thanks for your bug report.
But without any of these additional information I am not able to find the reason for this issue to fix it.
Can you provide some more info?
Does anyone else have a similar problem?

**Comment by Starcommander** [comment]
No response, closing now.
