### ISSUE TITLE
releases not showing in play store or fdroid

### ISSUE THREAD

**Issue by feelingwalnut** [junjunguo/PocketMaps#148]
The most current release in either is 3.4
But source is published here for 3.5 and 3.6
If memory serves this was not intentional but an issue with fdroid building?
Thanks

**Comment by Starcommander** [comment]
Hello @feelingwalnut Yes, it has to do with fdroid building issue.
I am also not happy, that a rebuild needs a month.
As soon as we get a new version on f-droid I will also release in play store.
So I think we have to wait 2 more weeks.

The last build has failed:
https://f-droid.org/wiki/page/com.junjunguo.pocketmaps/lastbuild_36

I made changes, and re-tagged the version 3.7
https://gitlab.com/fdroid/fdroiddata/-/issues/2057

**Comment by Starcommander** [comment]
Finally Version 3.7 is now released on F-Droid.
Playstore will follow soon.

**Comment by feelingwalnut** [comment]
this will be good as 3.7 was fully functional in my 300mile trip. aside from areas being an unknown speed which didn't matter since I was driving double the limit most of the time.

only complaint is navigation destination is so granular that i never actually reach a destination (i either drive past or never fully arrive) to see what happens to navigation. 
does it say or do anything special?

**Comment by Starcommander** [comment]
@feelingwalnut Thanks for sharing your experience.
No, the navigation does not stop automatically. ;)

**Comment by feelingwalnut** [comment]
then navigation is working as intended.
