### ISSUE TITLE
outdated version in Google Play store for Germany

### ISSUE THREAD

**Issue by mi-hol** [junjunguo/PocketMaps#150]
there seems to be only an outdated version from  3rd Feb 2020 available in Google store for Germany.
When installed on mobile the 'about' dialog doesn't show a version unfortunately

Could an .apk file be made available here for the released version too?

**Comment by mi-hol** [comment]
https://github.com/junjunguo/PocketMaps/issues/147 might be related

**Comment by feelingwalnut** [comment]
When i compiled latest, simply download android studio, download pocketmap source,open source in studio and compile. Studio will handle downloading dependencies.

It is a lot of data to download but it easy, most is done for you

**Comment by Starcommander** [comment]
Or on linux you can use the build-script instead.
- PocketMaps/mapGenerator/compile_copy_paul.sh
The script depends on gradle and android-sdk without android-studio.

APK added:
- https://github.com/junjunguo/PocketMaps/releases/tag/3.7

**Comment by mi-hol** [comment]
@Starcommander, thanks for providing the apk on github.
Unfortunately pocketmaps will be useful only after fixing #145

**Comment by Starcommander** [comment]
@mi-hol  Maps downloading should work.
If you have troubles, then please provide some additional information on #145 
- Android version
- What exactly is the problem
- What happens
- Logcat output (if possible)
- and so on ...

**Comment by Starcommander** [comment]
Finally Version 3.7 is now released on F-Droid.
Playstore will follow soon.
