### ISSUE TITLE
Version number not displayed in About dialog

### ISSUE THREAD

**Issue by mi-hol** [junjunguo/PocketMaps#151]
Would it be feasible to integrate code similar to what is mentioned on http://www.envyandroid.com/get-android-versioncode-and-versionname/#accessingit in pocketmaps about dialog?

**Comment by Starcommander** [comment]
@mi-hol Thanks for your hint.
Basically you can find the version on android-->settings-->apps.
But you are right, the version should also be visible in about-dialog.

**Comment by Starcommander** [comment]
Version is showing in first line: Instead PocketMaps now: PocketMaps v3.8
Fixed in next release.
