### ISSUE TITLE
Incorrect map attribute

### ISSUE THREAD

**Issue by alphanmoon** [junjunguo/PocketMaps#152]
Crimea is an Ukrainian Autonomous Republic of Crimea, not a Russian fed district.
![Screenshot_20200921-015419](https://user-images.githubusercontent.com/25549734/93724198-9cfd9580-fbad-11ea-8295-942044606d74.jpg)
.

**Comment by feelingwalnut** [comment]
This may be an OSM issue as when you search crimea on openstreetmaps it comes up as russia federation.
It also means you may be able tocorrect it yourself by contributing an edit to OSM

My understanding is pocketmaps merely downloads map assets from that source.

**Comment by feelingwalnut** [comment]
This may be an OSM issue as when you search crimea on openstreetmaps it comes up as russia federation.
It also means you may be able to correct it yourself by contributing an edit to OSM
Link mostly related.
https://www.openstreetmap.org/relation/7750160#map=6/45.187/34.431

My understanding is pocketmaps merely downloads map assets from that source.

**Comment by Starcommander** [comment]
That is right.
Pockemaps relies on external websites while building maps.
I do not plan to do something special there.
