### ISSUE TITLE
Break down Spain maps

### ISSUE THREAD

**Issue by pataquets** [junjunguo/PocketMaps#153]
As of now, Spain is 1,7gb which, even for today's standards is quite a lot to ask a user to spend, especially when compared with other alternatives requiring way less space. Even for those of us who prefer FLOSS alternatives.
Spain could be subdivided into Autonomous Communities and deeper in provinces (the most common).

**Comment by feelingwalnut** [comment]
at the speeds the server provides, it would be a long download.
maybe it is possible to break spain into 2-3 parts? north, (central) and south?

**Comment by pataquets** [comment]
Of course, it would be better than nothing. But truth is, sounds quite patchy and that might lead to some provinces split and ended up divided among two maps
Disclaimer: I was not aware that a finer subdivision entails that much more processing. Honestly, I'm not familiar off how maps are generated here. It's this documented anywhere?

**Comment by feelingwalnut** [comment]
i'm not 100% sure but playing with different services that enable download of OSM maps, it is a pain in the ass to make territory.
America is broken into states, it should be possible to treat Spain the same way.

we will have to wait for input from dev.

**Comment by Starcommander** [comment]
I have modified the script to split the spain-map to north and south.
Also I will update all other maps next time, but this will take some weeks.

**Comment by feelingwalnut** [comment]
Starcommander inadvertantly starts spanish civil war.

**Comment by Starcommander** [comment]
Spain is separated now into north and south.
