### ISSUE TITLE
Saving Favorite locations

### ISSUE THREAD

**Issue by hunterstabler** [junjunguo/PocketMaps#154]
I've encountered a bug where the program crashes when I try to save a favorite location or try to use a favorite location as origin or destination. Really loving the app otherwise. Running on Lineage OS updated days ago. I don't know how to post developer error logs because I am new to the scene.

**Comment by Starcommander** [comment]
Most likely it has to do with your **Favourites.properties** file.
Maybe you can post the content of this file?
You can find the file on the selected maps-storage location.
(Settings are on the three-dots-menu)
You can also send to my email-address soundmodul at gmx.at

**Comment by Starcommander** [comment]
@hunterstabler Do you have any news about the Favourites issue?

**Comment by Starcommander** [comment]
No response, closing.
