### ISSUE TITLE
Cannot find EncodedValue foot_network

### ISSUE THREAD

**Issue by innodeltech** [junjunguo/PocketMaps#157]
Android Studio Error : 
ERROR: An error happened while creating graph:DefaultEncodedValueFactory cannot find EncodedValue foot_network

Please help...

**Comment by Starcommander** [comment]
Need more information.
- When does this error occur?
- What exactly are you doing?
I do not use AndroidStudio.
Compiling and transfer to mobile is done by the script mapGenerator/compile_copy_paul.sh
