### ISSUE TITLE
Version of edges unsupported: 

### ISSUE THREAD

**Issue by innodeltech** [junjunguo/PocketMaps#158]
Android Studio error : 
An error happened while creating graph:Version of edges unsupported: 17, expected:15. Make sure you are using the same GraphHopper version for reading the files that was used for creating them.

**Comment by Starcommander** [comment]
@innodeltech 
Need more information.
- When does this error occur?
- What exactly are you doing?
I do not use AndroidStudio.
Compiling and transfer to mobile is done by the script mapGenerator/compile_copy_paul.sh
