### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [junjunguo/PocketMaps#160]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Starcommander** [comment]
Good idea.

**Comment by Starcommander** [comment]
Done.
Next steps:
Cleaning up as suggested in https://gitlab.com/fdroid/fdroiddata/-/issues/2657
Draft a new release (4.0).
