### ISSUE TITLE
Android Car Head Unit Wrong UI scaling

### ISSUE THREAD

**Issue by colmoschin94** [junjunguo/PocketMaps#161]
Hi,
On my Android car head unit UI seems not to be scaled correctly, specifically not all the navigation options can be seen (eg. Smooth ride, aka Kalman GPS is missing) and no scroll is possible.

Display resolution is 1024*600

Can this issue be fixed?

Thanks 

![IMG_20210126_123449](https://user-images.githubusercontent.com/16521628/105842130-ffd8c080-5fd5-11eb-80ef-239286c6e899.jpg)

**Comment by Starcommander** [comment]
@colmoschin94 
Basically this issue can be fixed.
We have to implement landscape resolutions.
But this is some work.

Would you make some beta-tests then?

**Comment by colmoschin94** [comment]
Sure I can,
Just send me a modified APK and I'll test it :)

Thanks!

Matteo

Il ven 5 feb 2021, 00:27 Paul Kashofer <notifications@github.com> ha
scritto:

**Comment by Starcommander** [comment]
I added a scrollView, because it was easy to implement, and also fits devices with low resolution.
Please try to install the app from attachment.
Maybe you have to uninstall Pocketmaps first.
(Not tested)

[pocketmaps-debug.zip](https://github.com/junjunguo/PocketMaps/files/5978550/pocketmaps-debug.zip)

**Comment by colmoschin94** [comment]
Thanks, I'll check it out and report back ;)

Matt

Il dom 14 feb 2021, 22:20 Paul Kashofer <notifications@github.com> ha
scritto:

**Comment by colmoschin94** [comment]
All works!

Thanks for the help ;)

Matt

Il dom 14 feb 2021, 22:43 Matteo Cantarella <colmoschin94@gmail.com> ha
scritto:
