### ISSUE TITLE
import_maps_paul.sh -i fails to complete

### ISSUE THREAD

**Issue by happysmash27** [junjunguo/PocketMaps#163]
I am trying to download the maps to an SD card from a computer, in order to be used on an Android car console which is not connected to the internet. 

Trying to run the command which I think will allow this, results in several errors: 

```
 $ bash ./import_maps_paul.sh -i
Starting ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40716  100 40716    0     0  68086      0 --:--:-- --:--:-- --:--:-- 68086
Finish! Get the maps from /tmp/graphhopper_0-13-0/maps-osm/
==================================
Wed Apr 14 04:32:09 PDT 2021
Starting with map europe/albania-latest.osm.pbf
Continue? y=yes b=break a=yesToAll
          s=skip w=skipWhooleContinent
>>>a
df: '': No such file or directory
./import_maps_paul.sh: line 264: [: : integer expression expected
sed: can't read config.yml: No such file or directory
./import_maps_paul.sh: line 296: ./graphhopper.sh: No such file or directory
Graphhopper returned an error!
Error, path is missing: /tmp/graphhopper_0-13-0/maps-osm/europe_albania-gh/nodes_ch_fastest_car_node
```

The instructions are not too clear to me, so I may be following them wrong, maybe missing a dependency. Does anyone have any suggestions on how to fix this, or is there another way to import the maps manually?

**Comment by Starcommander** [comment]
Hello @happysmash27 
This script will not only download, but also transcode the map data for use in pocketmaps.
All you need is documented in the header.
Better: You can also download the maps from my server directly.
http://vsrv15044.customer.xenway.de/maps/

Best regards,
Paul

**Comment by Starcommander** [comment]
I have changed the script.
Should now work without using a server.
(but not tested yet)
