### ISSUE TITLE
OSM search is not present!

### ISSUE THREAD

**Issue by octavo** [junjunguo/PocketMaps#166]
OSM search doesn't work anymore. Google's works, though. 

PocketMaps 3.7
Android 11

![Imagepipe_0.jpg](https://user-images.githubusercontent.com/1730033/137153356-3d25e03a-a961-4a51-8fd3-c3abddf60bcd.jpg)

**Comment by Starcommander** [comment]
@octavo 
Thanks for your report!
On my phone the osm-search-engine is working, so it has not to do with online service.
Did you try it multible times, and does the search never work?
And did you try different inputs, maybe it has to do with special chars?

Maybe anyone else does have such an issue with search-engine?

Best regards.

**Comment by octavo** [comment]
@Starcommander It has worked in the past but now it doesn't.

@feelingwalnut OSM.org works fine and it has worked in the past.
