### ISSUE TITLE
Cant download maps

### ISSUE THREAD

**Issue by zah0** [junjunguo/PocketMaps#169]
So i tried to download central-fed-district in app and it failed, tried to change the folders and it still wouldnt work, and so i stumbled upon the manual download from the server in here, tried to download, and i got the "The requested URL was not found on this server." 404 error. Is there any way to download the map?

**Comment by zah0** [comment]
its suddenly fixed? I guess I just had to wait

**Comment by Starcommander** [comment]
Yes, I updated all maps.
Temporary I had to clean up the server for low memory reason.
