### ISSUE TITLE
Can't download italian maps

### ISSUE THREAD

**Issue by gisep** [junjunguo/PocketMaps#170]
Hi, i try to download one of the italian maps (south, centre, north-west, north-east or islands) but the mobile phone vibrates and scrolling down the notifications it appears (without the '):

<'Senza nome>
Download non riuscito

Maybe the link is broken?

Edit:
This is the link:
http://vsrv15044.customer.xenway.de/maps/maps/2020-12/europe_italy_sud.ghz

As i click on this, it appears:
Not Found

The requested URL was not found on this server.
Apache/2.4.38 (Debian) Server at vsrv15044.customer.xenway.de Port 80

**Comment by gisep** [comment]
i tried again and it downloaded the maps with no problem.

**Comment by Starcommander** [comment]
Yes, I updated all maps.
Temporary I had to clean up the server for low memory reason.
