### ISSUE TITLE
Poland map missing or redirect failing

### ISSUE THREAD

**Issue by doosom** [junjunguo/PocketMaps#171]
Hi all.

I have setup a new phone and was able to download all Spanish and a few German maps but on the Polish map the download fails. I have checked http://vsrv15044.customer.xenway.de/maps/ and the link to the europe_poland.ghz is not working. Are you able to help?

Thanks in advance!

**Comment by Starcommander** [comment]
@doosom 
Thanks for reporting this bug.
Seems the redirect-link was broken.
A lot of maps were affected. (30)
Should be fixed on server now.

**Comment by doosom** [comment]
It's working again.  Thanks for fixing! :)
