### ISSUE TITLE
Error download map

### ISSUE THREAD

**Issue by rhp7rholype** [junjunguo/PocketMaps#173]
Error 404, when I try download map Belarus:
http://vsrv15044.customer.xenway.de/maps/maps/2022-01/europe_belarus.ghz
Thank You.

**Comment by Starcommander** [comment]
Also affected:
[2022-01 europe_azores.ghz](http://vsrv15044.customer.xenway.de/maps/maps/2022-01/europe_azores.ghz)

**Comment by Starcommander** [comment]
Done:
http://vsrv15044.customer.xenway.de/maps/maps/2022-04/europe_azores.ghz
(Belarus in progress ...)

**Comment by Starcommander** [comment]
Done:
http://vsrv15044.customer.xenway.de/maps/maps/2022-04/europe_belarus.ghz
@rhp7rholype Thanks for creating this issue.
