### ISSUE TITLE
Description issue on F-Droid

### ISSUE THREAD

**Issue by asa-0** [junjunguo/PocketMaps#192]
The app description on F-Droid is "Unknown application."

That can probably be improved upon!

I'm told that to do that you "just need a new tag". (I didn't ask for elaboration).

Thanks!

**Comment by Starcommander** [comment]
Sorry for the late response.
Now - one year later - i created a new version and a new tag.
Hope we can see the description again.

**Comment by Starcommander** [comment]
New version is out, and description visible on f-droid.
