### ISSUE TITLE
Can't use ohter vehicle options for routing 

### ISSUE THREAD

**Issue by IoannisSvolosBht** [junjunguo/PocketMaps#196]
Hi :) how can I integrate e.g. motorcycle as a vehicle option in the app? bike, foot and car are only working. I mean the MotorcycleFlagEncoder exists under graphhoper 0.13.0. What things do I have to change or add? I am currently working with Android Studio.

**Comment by feelingwalnut** [comment]
out of sheer curiosity, is there really a difference between motorcycle routes and car routes?
are you allowed to take them places you can not take a car?

**Comment by Gianni1012132** [comment]
Motorcycle was only an example. I was hoping to get a solution to change the vehicle profile option in the app. I mean pocketMaps is based on GraphHopper so if i'm not mistaken it should support all other vehicle/profiles (FlagEncoders) like hiking, mountainbike, motorcycle etc.

**Comment by Gianni1012132** [comment]
> out of sheer curiosity, is there really a difference between motorcycle routes and car routes? are you allowed to take them places you can not take a car?



> out of sheer curiosity, is there really a difference between motorcycle routes and car routes? are you allowed to take them places you can not take a car?

Motorcycle was only an example. I was hoping to get a solution to change the vehicle profile option in the app. I mean pocketMaps is based on GraphHopper so if i'm not mistaken it should support all other vehicle/profiles (FlagEncoders) like hiking, mountainbike, motorcycle etc.

**Comment by Gianni1012132** [comment]
> out of sheer curiosity, is there really a difference between motorcycle routes and car routes? are you allowed to take them places you can not take a car?

Motorcycle was only an example. I was hoping to get a solution to change the vehicle profile option in the app. I mean pocketMaps is based on GraphHopper so if i'm not mistaken it should support all other vehicle/profiles (FlagEncoders) like hiking, mountainbike, motorcycle etc.

**Comment by Starcommander** [comment]
In java code: See the enum "**Variable.TravelMode**" , and where it is used.

But it is not that easy.
Each TravelMode has to be included into the Map, that you get from our servers.
And we have only included "Car" "Bike" and "Foot" into our maps.
See line 117 in **import_maps_paul.sh** where I replace **car** only to **car,bike,foot** in the configs.
Also the included travelModes will need disk-space, this is why I do not plan to include more.
