### ISSUE TITLE
Envioronment

### ISSUE THREAD

**Issue by Abhis-123** [junjunguo/PocketMaps#199]
Sorry, For  silly this question , I am new to this android developement. is there any docs added  which have some quick guide on its developement environment. 

PS; I want to use it for myself, where i will be using a modified pbf files.

**Comment by Starcommander** [comment]
You can just use **gradle** to build the app, and any environment that supports gradle.
(Eclipse, NetBeans, ...)
Just enter PocketMaps directory and execute **./gradlew build**, or on Windows **gradlew.bat build**
You can also look at the script, that I use: **mapGenerator/compile_copy_paul.sh**
