### ISSUE TITLE
Android Scoped Storage changes to android 11+ devices

### ISSUE THREAD

**Issue by deepak07dbz** [junjunguo/PocketMaps#200]
How did this project adapted to scoped storage changes for android 11+ devices, since graphhopper(https://discuss.graphhopper.com/t/integration-graphhopper-in-android-with-mapforge/6764/8) says they stopped support for offline navigation in android.

**Comment by Starcommander** [comment]
I still use the older version of graphhopper 0.13.0 that has all features I need for pocketmaps, and supports android.
The latest version of graphhopper, that also supports android is 1.0

And regarding storage I had to modify code of pocketmaps multiple times to work on old and new Android versions.
You find that in file **PocketMaps/app/src/main/java/com/junjunguo/pocketmaps/util/IO.java**

Best regards,
Paul
