### ISSUE TITLE
[ANDROID] Need help! tileSource.getMapInfo() gives null pointer exception while loading map?

### ISSUE THREAD

**Issue by deepak07dbz** [junjunguo/PocketMaps#201]
void loadMap(File areaFolder) {
        logUser("loading map");

        // Map events receiver
        mapView.map().layers().add(new MapEventsReceiver(mapView.map()));

        // Map file source
        MapFileTileSource tileSource = new MapFileTileSource();
        //File mapFile = new File(areaFolder, currentArea + ".map").getAbsoluteFile();
        tileSource.setMapFile(new File(areaFolder, currentArea + ".map").getAbsolutePath());
        //Log.d("LOAD", "loadMap: " + );
        Log.d("LOAD", "loadMap: " + tileSource);
        VectorTileLayer l = mapView.map().setBaseMap(tileSource);
        mapView.map().setTheme(VtmThemes.DEFAULT);
        mapView.map().layers().add(new BuildingLayer(mapView.map(), l));
        mapView.map().layers().add(new LabelLayer(mapView.map(), l));

        // Markers layer
        itemizedLayer = new ItemizedLayer(mapView.map(), (MarkerSymbol) null);
        mapView.map().layers().add(itemizedLayer);

        // Map position
        GeoPoint mapCenter = tileSource.getMapInfo().boundingBox.getCenterPoint();
        mapView.map().setMapPosition(mapCenter.getLatitude(), mapCenter.getLongitude(), 1 << 15);

        setContentView(mapView);
        loadGraphStorage();
    }

where tileSource.getMapInfo() gives nullPointerException although the file exists and the path is correct. And loadMap() is called when write_external_storage permission is granted.
Did you face this issue or can you help me?

**Comment by deepak07dbz** [comment]
//getting path and permission code
 File baseDir;

        if (Build.VERSION.SDK_INT >= 29)
        { // ExternalStoragePublicDirectory Deprecated since android Q
            baseDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
            if (!Environment.getExternalStorageState(baseDir).equals(Environment.MEDIA_MOUNTED))
            {
                Toast.makeText(this, "Not usable without an external storage!", Toast.LENGTH_SHORT).show();
                baseDir = null;
            }
        }
        else if (Build.VERSION.SDK_INT >= 19)
        { // greater or equal to Kitkat
            if (!Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED))
            {
                Toast.makeText(this, "Pocket Maps is not usable without an external storage!", Toast.LENGTH_SHORT).show();
                baseDir = null;
            }
             baseDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        }
        else
        {
            baseDir = Environment.getExternalStorageDirectory();
        }

        if (baseDir != null) {
            mapsFolder = new File(baseDir, "/graphhopper/maps/");
            Toast.makeText(this, mapsFolder.toString(), Toast.LENGTH_SHORT).show();
        }
        if (!mapsFolder.exists())
            mapsFolder.mkdirs();

        if (ContextCompat.checkSelfPermission(this, android.Manifest.permission.WRITE_EXTERNAL_STORAGE)
                != PackageManager.PERMISSION_GRANTED) {
            // Permission is not granted, request it
            ActivityCompat.requestPermissions(this,
                    new String[]{android.Manifest.permission.WRITE_EXTERNAL_STORAGE},
                    WRITE_PERMISSION_CODE);
        } else {
            // Permission has already been granted, proceed with accessing the file
            chooseArea();
        }
    }

    private void chooseArea(){
        prepareInProgress = true;
        final File areaFolder = new File(mapsFolder, currentArea + "-gh");
        Log.d("OPEN", "chooseArea: " + areaFolder);
        Log.d("OPEN", "opening file");
        loadMap(areaFolder);
    }

**Comment by Starcommander** [comment]
Has this anything to do with pocketmaps?
What maps are you using?
Where are the code snippets from?
Also missing: the log output with exception.

**Comment by Starcommander** [comment]
Closing, as no response.
