### ISSUE TITLE
Freelance Offering 

### ISSUE THREAD

**Issue by abhisheskbdm** [junjunguo/PocketMaps#202]
Guys I am interested in developing an application similar to this, with ability to import some extra latitude and longitude locations (along with a description.  for the search ) from a CSV file.As I am assuming that it would not require much changes in existing application.

**Comment by Starcommander** [comment]
Then checkout PocketMaps, and make your changes.
PocketMaps is free and open source, so you are free to modify the app.
If your changes are good, it is helpful to make a PullRequest to merge the changes into the main app.
