### ISSUE TITLE
process bar to show map download process

### ISSUE THREAD

**Issue by junjunguo** [junjunguo/PocketMaps#25]

**Comment by stephan75** [comment]
@junjunguo and @Starcommander 

I have Pocketaps app version 2.0 from Playstore with date 29.03.2018, but in these days of beginning September 2018 I have absolutely no progress indicator when downloading a map file from the list of all maps available. This happens even with small map files with only a few MBytes filesize.

On an android 5.X device with SD card, also tried to change map saving directory inside pocketmaps app.

What can I do?

**Comment by Starcommander** [comment]
Basically we use the android-download-manager in new version.
So the progress should be visible in the taskbar on the top.
Do you have a good internet connection (wlan)?
Maybe you have installed any firewall that blocks the android-download-manager?
What is your location, where you try to download?

**Comment by Starcommander** [comment]
And finally: does the download finish without progress bar?

**Comment by stephan75** [comment]
Finally i was able to download a map file for part of Germany,

But only after switching download path from SD card to internal memory!

Seems that the app is not able to have write access to SD card.
