### ISSUE TITLE
Split Brazil into states/regions

### ISSUE THREAD

**Issue by naoliv** [junjunguo/PocketMaps#48]
Could the Brazil map be split into states (or at least regions), please?

**Comment by junjunguo** [comment]
I will get to this one when I get time :)

**Comment by naoliv** [comment]
Because Brazil is too big (which translates into more data being downloaded and unneeded space being used in the phone).
Most of the time we don't need to have all the country downloaded.
Regions (`admin_level=3` in OSM) or States (`admin_level=4`) are usually what 99% of the users will need.

**Comment by Starcommander** [comment]
Hello @naoliv !
Unfortunately there are no admin-levels of brazil on geofabrik.de
So I have to split it manually.
As I understand this correct there are 5 parts to split:
- south, south-east, north, north-east, middle-west
I added Brazil-s (south) to list.
Please try and test.

**Comment by Starcommander** [comment]
I removed Brazil and added instead:
- brazil-n
- brazil-s
- brazil-ne
- brazil-se
- brazil-cw

Please test and comment.

**Comment by naoliv** [comment]
Very good! Thanks!
