### ISSUE TITLE
Are play services necessary?

### ISSUE THREAD

**Issue by twzkxkan** [junjunguo/PocketMaps#51]
Is it possible to create a build without the proprietary components?

**Comment by junjunguo** [comment]
Hi @twzkxkan do you mean the Google analytics services? Yes, I will remove them at next update.

**Comment by pizzamaker** [comment]
Play Services needs to be dropped for its inclusion in F-Droid: https://f-droid.org/forums/topic/pocket-maps/

**Comment by junjunguo** [comment]
Thanks @twzkxkan and @pizzamaker! 
Play services removed :)

**Comment by twzkxkan** [comment]
Thanks!
