### ISSUE TITLE
Spain and France are not available for downloading

### ISSUE THREAD

**Issue by moshpirit** [junjunguo/PocketMaps#55]

**Comment by nico202** [comment]
Italy is missing too

**Comment by junjunguo** [comment]
Hei, @moshpirit  & @nico202 , you can also generate your own maps :)

**Comment by moshpirit** [comment]
Hi, thanks for answer us. 

1. Why not just using the actual OSM maps? 
2. How could we generate new maps?

**Comment by junjunguo** [comment]
Hi @moshpirit 
1. This project uses OSM data, Mapsforge and Graphhopper open source API, the APIs allows offline routing, so the maps has to be specified. but I'm considering to use other APIs ...
2. check 'How to create map' at README.md

**Comment by nico202** [comment]
@junjunguo thanks, where can we upload them then to make them available to others?
Ps. Thanks for the app :)

**Comment by junjunguo** [comment]
hi @nico202 Thanks for being so kind :)
but one of the problem is that I do not have enough cloud space for uploading maps :(
ps. you are welcome :)

**Comment by ilmich** [comment]
hi @junjunguo, thanks for your app :) 
I'm an junior android developer and I want to contribute.
I've some cloud space for italy maps (and maybe others country).. When I've done I'll share the location and if you want you can add the url in your map list source.

Regards
Michele

**Comment by junjunguo** [comment]
Hi @ilmich Thank you very much for being so kind :)
It would be great if you can share the the maps :+1: .
I will add the url in the map list if you make them ready :)

I'v already add the your comments to README :) thanks for this!

Best greetings

**Comment by ilmich** [comment]
Hi @junjunguo my repository of maps is available at this url

http://www.portaxxv.org/pocketmaps/

for now there is only the whole italy map, but soon I'll generate smaller maps of regions (and maybe of biggest city) and also other countries (like Spain and France)

Try it, I've not tested download my map with app (tested only with manual installation) but it should work (I'm using nginx as webserver, but I've noticed that app parse href and then sould be fine)

Tell me if something goes wrong :)
Cheers
Michele

**Comment by junjunguo** [comment]
Hi @ilmich Thank you for your contribution, I will do a test and give you feedback about it :)

**Comment by junjunguo** [comment]
hi @ilmich , can you change the map extension to '.ghz'

**Comment by ilmich** [comment]
done:) sorry for the mistake

**Comment by junjunguo** [comment]
hei @ilmich , thanks for your help, can you help me to generate a map for Spain ? :)

**Comment by ilmich** [comment]
I've generated Spain map and uploaded it on my cloud space.

**Comment by junjunguo** [comment]
Hei @ilmich , thank you very much for the map :+1: 

I have add you as a contributor so you have read write right to PocketMaps :)

Next update will be pocketMaps v9, version 1.8, it's in the branch 'pocketmaps_v9', master branch is holding released version, which is tested and stable, push to master when you think we should do a release :)

Welcome to PocketMaps, lets make PocketMaps better :)

Best greetings 

Junjun Guo

**Comment by junjunguo** [comment]
Hei @ilmich, did you tested the map for spain ? (doesn't show map in my mobile).

**Comment by moshpirit** [comment]
Wow thank you very much!

**Comment by ilmich** [comment]
Hi @junjunguo, this is spain map on my device

![screenshot_2015-10-25-12-30-05](https://cloud.githubusercontent.com/assets/148796/10715387/9516f37a-7b15-11e5-820f-d73d2e439830.png)

and thanks for adding me as contributor. Hope that my contributions can be useful :)

Regards
Michele

**Comment by junjunguo** [comment]
Thanks @ilmich :) take some time to load the map with my device, but I got it too :)

There is some problem with download from your server, I will try to fix it later. In the meantime, I borrowed some cloud space and copied Italy and Spain from your server to mine, so people have Spain and Italy maps to use. 

Best greetings

**Comment by ilmich** [comment]
Hi @junjunguo , no problem for me :) 
My first task on PoketMaps is to help you in implementing, if you think that it's useful, downloading also from other maps repos ( as #58 ).
I've also started to split my Italy map into smaller piece, because on some devices, storage is not enough :)

Michele

**Comment by junjunguo** [comment]
Thanks  @ilmich, It is important to have smaller maps, it's very useful :+1: 

Best greetings 

Junjun

**Comment by adelta** [comment]
Hi @ilmich ,can you help me to create iran map in the project?
