### ISSUE TITLE
PocketMaps crashes when trying to load France map

### ISSUE THREAD

**Issue by RiZom-91** [junjunguo/PocketMaps#60]
Hi,

I've tried to create the map folder for my country (France) by myself, as it was not available yet. I've followed the instructions in the ReadMe file.

- graphhopper 0.4.1
- latest france.osm.pbf
- latest france.map

Unfortunately, PocketMaps crashes almost each time I try to load the map. Sometime it seems to work and can see the map but most of the time it crashes. Plus, if it works and I try to start the navigation, it crashes too.

Please note, I had to rename the folder to europe_France-gh and the .map file to europe_France.map, otherwise PM was crashing while the app was starting.

Did someone experience something like this before ? Is there a log file or something I could get to help ?

Cheers,
RiZom-91

**Comment by RiZom-91** [comment]
I've noticed there is an error notification in the background.

An error happened while creating graph: Couldn't map buffer <?> of 59 at position <?> for <?> bytes with offset 100, new file length <?>

The <?> are numbers that are changing each time.

It seems to not crash only when I've just downloaded and opened another map (Switzerland), but the error message still appears.

Hope it helps! :)

**Comment by junjunguo** [comment]
hi @RiZom-91  try to download the new France maps I just uploaded :)

**Comment by RiZom-91** [comment]
Thank you it works better! Is it because my map was to big (3.0GB) or did I fail to follow the steps explained in the ReadMe file ? By the way there is still an error notification with your map, but it works anyway!

Now, I'm trying to test the navigation feature but when I choose "Point on map" the controls are being hidden and touching the map doesn't do anything (except move or zoom in/out).

I have to kill the app because the menu is not visible anymore and the return key just hide the app.

**Comment by junjunguo** [comment]
sometimes you just have to kill the app the release you memory to make it work agin, for some big maps some mobile might not able to load the map, because there isn't enough memory ...
(to generate maps you need grafhopper 4.0, not 5.0 and set car, foot, bike, it's on the readme) :)
