### ISSUE TITLE
Maps download

### ISSUE THREAD

**Issue by JairLeBentz** [junjunguo/PocketMaps#61]
Hi! 
I installed this app from F-droid.
When I try to start, I choose download a map but  nothing happens.
really nothing.
I try to download with  Wifi + GPS or without GPS too but the App does nothing.

Thanks for your work
Jairo

**Comment by junjunguo** [comment]
Hi @JairLeBentz , thanks for your feedback, can you write your android version and brand as well ?

Best greetings 

JunjunGuo

**Comment by JairLeBentz** [comment]
My Phone is a Fairphone 1U 
Android version 4.2.2
Kernel-Version 3.4.5
thanks for your answer

**Comment by junjunguo** [comment]
Thank you for your feedback and open an issue :)

**Comment by lhark** [comment]
Same problem here in the fdroid version (1.7) on an Xperia ray, android 4.0.4, kernel 2.6.32.9-perf

**Comment by Nprod** [comment]
Same problem for me too, Huawei Y300, Android 4.1.1, kernel 3.4.0-perf-g6031273. Tried both the Fdroid and the regular version - same thing. Progress bar shows, then blank screen.

**Comment by albsod** [comment]
Same problem here. I'm running Replicant version 4.2 0004, based on Android version 4.2.2 on a Samsung Galaxy S2.

**Comment by contrapunctus-1** [comment]
I too experience this (v2.0, F-Droid, Nokia 6.1/Android 8.1).

**Comment by Starcommander** [comment]
@contrapunctus-1 
Is 2.0 the version of your pocketmaps app?
After selecting the plus-button what happens?
Which map did you try to download?
Did you select the map-Icon for downloading?
Did the download appear on status-bar?
What exactly happened?

**Comment by contrapunctus-1** [comment]
@Starcommander 
> Is 2.0 the version of your pocketmaps app?
Yeah.
> After selecting the plus-button what happens?
I get a list of countries.
> Which map did you try to download?
India.
> Did you select the map-Icon for downloading?
I pressed the cloud button.
> Did the download appear on status-bar?
It did not.
> What exactly happened?
The cloud button turned into a pause button. The text "Downloading..." appeared.

**Comment by Starcommander** [comment]
Do you have a good internet connection on your mobile phone?
Wifi or via mobile net?
Or is it possible, that you have installed any firewall-app?
In this case the Download-Manager of Android needs access.

**Comment by contrapunctus-1** [comment]
I'm on a fairly reliable personal WiFi. All my applications are from F-Droid, and I don't think I have anything installed which could be considered a firewall :)

I also tried to download the maps by pointing my phone's browser to
http://vsrv15044.customer.xenway.de/maps/ and downloading the data for India there. But whenever I'd point PocketMaps to look for the map data in a folder containing the file, it'd just crash on startup ._.

**Comment by contrapunctus-1** [comment]
Sigh, I can't reproduce the crash. But now, no matter where I put the downloaded map file (asia_india.ghz) - 
/storage/emulated/0/Android/media/com.junjunguo.pocketmaps/
/storage/emulated/0/Android/media/com.junjunguo.pocketmaps/pocketmaps/
/storage/emulated/0/Android/media/com.junjunguo.pocketmaps/pocketmaps/maps/
...the app doesn't detect it 😔

**Comment by Starcommander** [comment]
Please look at way2 --> "Now copy the bundle to your Android device"
https://github.com/junjunguo/PocketMaps/blob/master/documentation/create_maps.md

Be aware because of bug #82
https://github.com/junjunguo/PocketMaps/issues/82

**Comment by natrius** [comment]
Here, also from F-Droid, its working.

**Comment by Starcommander** [comment]
Should be more stable now.
I changed the visibility of download-notification to permanent.
Since v2.2
