### ISSUE TITLE
Can't build maps for Australia

### ISSUE THREAD

**Issue by GeddesJ** [junjunguo/PocketMaps#80]
I am slightly disappointed that there are no maps available to download for Australia, however the instructions to create maps seemed simple enough. I was able to use the import_maps_paul.sh script to generate the maps for Australia, however when copying over to the device and loading with Pocket maps it says that the map is not compatible. 
I am running Pocket Maps from FDroid on Lineage OS 15.1 (Android 8.1)

**Comment by Starcommander** [comment]
Thanks for your report.
Seems I have really forgotten to include Australia.
I will include that maps soon.

To get your created map working you also have to create a version file:
- Filename: /storage/Android/media/com.junjunguo.pocketmaps/pocketmaps/maps/cont_country-gh/version.txt
- File content: 0.9.0_1

I am also working on a new version, where it is no more necessary to create this file.

**Comment by Starcommander** [comment]
I have added Australia now.
Best regards

**Comment by GeddesJ** [comment]
Thanks very much! I can confirm that the maps for Australia work.
