### ISSUE TITLE
Crash when moving map to download folder manually

### ISSUE THREAD

**Issue by Starcommander** [junjunguo/PocketMaps#82]
PocketMaps crashes when you download a map.ghz and put it into the download folder manually.

As a workaround you can unpack the map instead into a created folder.
- Maps directory may be in: /storage/Android/media/com.junjunguo.pocketmaps/pocketmaps/maps/
- Inside maps folder create a new folder.
- Folder name must equal continent_country-gh

You also have to create a version file:
- Filename: maps/cont_country-gh/version.txt
- File content: 0.9.0_1

This bug will be solved in V2.1

**Comment by mobbydixk** [comment]
Hey, i tried doing this but it says my map need to be updated

**Comment by Starcommander** [comment]
@mobbydixk What is the version of your pocketmaps?
What is the content of the version.txt you created?
- Must be `<graphhopper-version>_<index>`, where index may be 0 or 1. (Not sure)
- Graphhopper-version is currently 0.13.0

Instead of creating a version.txt it is maybe more easily to copy the file from a different map.
