### ISSUE TITLE
[FR] Favorites: improve UI

### ISSUE THREAD

**Issue by ildar** [junjunguo/PocketMaps#83]
(once commented here: https://github.com/junjunguo/PocketMaps/issues/16#issuecomment-165243113 )
Favorites don't have a good UI right now. Need these improvements:
- [ ] Quick access to the list from the map
- [ ] A list item tap should bring to the location with proper zoom
- [ ] The list should be editable
- [ ] Import and export (OsmAnd format would be perfect)

**Comment by Starcommander** [comment]
Hello @ildar .
What exactly do you mean with Favourites?
The List where you can add custom places?
Or do you mean any different thing, or POIs?

The Favourite-List is already editable.
- You can add a Position with the plus-button.
- You can remove an entry with so called swipe-out

The Favourite-List is allready stored to sdcard, so no export is necessary.
You can already "quick-access" the list.
But maybe you mean something else?
What is the version you use currently?

**Comment by Starcommander** [comment]
I have added now some quick-buttons for faster access to favourites.

**Comment by ildar** [comment]
Thanks a lot!
but please reopen as not all points are done yet.

**Comment by Starcommander** [comment]
@ildar 
I will not reopen an issue, where is nothing to do.
Please explain exactly what you are missing.
In my opinion the only not finished part is already documented in #110 
And you have already the newest app-version installed?

Best regards,
Paul.

**Comment by ildar** [comment]
Yes, it's a matter of import/export.
#110 is good. But also smooth migration from OsmAnd would attract users.
Thanks for the app!

**Comment by Starcommander** [comment]
@ildar 
Do you have such an OsmAnd exported file?
Maybe I can check the content.
Would be helpful, if you can post such a file as example on Issue110.

Thanks in advance.
Paul
