### ISSUE TITLE
Can't pause download

### ISSUE THREAD

**Issue by naoliv** [junjunguo/PocketMaps#84]
It seems that we can't pause a map download.
While pressing the pause button it's possible to see a message saying `Already downloading!` (and the download just continues, without pausing).

**Comment by Starcommander** [comment]
Hello @naoliv !
I switched from an instable download-implemention to the Android DownloadManager.
So downloading in background works much better now.
In this implemention pause is currently not supported.
But I will try to reimplement the possibility to pause the map download.

**Comment by Starcommander** [comment]
Pause should now be available via Android DownloadManager in next version 2.1!
The problem was that download was sometimes not shown in task bar.
