### ISSUE TITLE
Map for Italy

### ISSUE THREAD

**Issue by surferjoeit** [junjunguo/PocketMaps#85]
Hello, i'd like to try the app but unfortunately there is no map for Italy available. I can't build it, is it possible to have it included?
Thanks

**Comment by Starcommander** [comment]
Hello @surferjoeit !
Thanks for your report.
You are right, italy is still missing.
I will try to add Italy the next days.

**Comment by surferjoeit** [comment]
Thanks!

**Comment by Starcommander** [comment]
Italy is included now.

**Comment by surferjoeit** [comment]
Many thanks, downloaded and tested right now (North west map), it's great.
Just One issue: i couldn't find any way to enable screen rotation. Isn't it allowed?
Thanks

Il 05 aprile 2018 22:10:43 CEST, Starcommander <notifications@github.com> ha scritto:
>Italy is included now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/junjunguo/PocketMaps/issues/85#issuecomment-379061439

-- 
Inviato dal mio dispositivo Android con K-9 Mail.
-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by surferjoeit** [comment]
Many thanks, downloaded and tested right now (North west map), it's great.
Just One issue: i couldn't find any way to enable screen rotation. Isn't it allowed?
Thanks

Il 05 aprile 2018 22:10:43 CEST, Starcommander <notifications@github.com> ha scritto:
>Italy is included now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/junjunguo/PocketMaps/issues/85#issuecomment-379061439

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by Starcommander** [comment]
Technically screen rotation is possible, but it is not implemented.

**Comment by surferjoeit** [comment]
Ok, thanks anyway.
