### ISSUE TITLE
Cannot open Great Britain map

### ISSUE THREAD

**Issue by GustavoLambert** [junjunguo/PocketMaps#88]
Hi,

I have downloaded it and installed it the map of Great Britain but it does not open. Whenever I try to open it the following message pops up : 

_Map is not compatible with this version! Please update map!_

However, I cannot find such option to update it.

I am using Android 6.0 in a Moto G (3rd gen).

P.S. Any other map I've tried works just fine...

**Comment by Starcommander** [comment]
Hi Gustavo!
Thanks for your report!
Can you please explain, what do you mean with "and installed it the map"?
And what is the version of your pocketmaps app?
Basically you can try to copy the version.txt file from one maps folder to the folder of Great Britain using a file browser.

**Comment by GustavoLambert** [comment]
I am sorry for the bad sentence. What I meant to say is that I had installed the app and the Great Britain map properly. I am using the latest version (2.0) available on F-Droid.

I am going to try your suggestion.

Thank you

**Comment by Starcommander** [comment]
Deleting a map is possible via swipe out.
Re-downloading the map should also be possible, when this message occurs.
Now I have improved the download-notification in v2.2
Best regards.
