### ISSUE TITLE
Smoothen the arrow-moving while navigating

### ISSUE THREAD

**Issue by natrius** [junjunguo/PocketMaps#90]
App Version: 2.0 (F-Droid)
Cellphone: OnePlus 3
Android: 8.1
OS: LineageOS 15.1

I was driving and it just hops from one point to another. I guess its everytime a GPS-location is discovered / gathered. If needed, i guess i can make a video too.

**Comment by hurradiegams** [comment]
> I decided to implement navigation in the easiest and most bug-save (and maybe also most accu-conserving) way.
> So I show the measured gps-location (sometimes off the street) instead of estimating, where you may drive.
> Video is not necessary, it is the default behaviour.

I would like to see this feature too, if possible.
If there is a feasible way to implement this maybe an extra option to set the feature asked for by natrius would be nice.

So the default behaviour would still be the same, but with an option to set a smoother option for following/tracking, maybe even with an automatism (also adjustable as an option) that automatically sets the smoother option if the phone is charging.
