### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Mehrankhan10** [junjunguo/PocketMaps#93]
when i click pop button then show me this erro 
there is problem in the server report the developer  
how can i resolve this issue ..i had updated each and every library kindly solve this issue for me 
Thank  you 

` defaultConfig {
        applicationId "com.navigation.trackingdirection.finder.free.offline"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.config
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation('com.graphhopper:graphhopper:0.4.1') {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'org.openstreetmap.osmosis', module: 'osmosis-osm-binary'
        exclude group: 'org.apache.xmlgraphics', module: 'xmlgraphics-commons'
    }
    implementation files('libs/heyzap-ads-sdk-9.6.10.jar')
    implementation 'org.mapsforge:mapsforge-core:0.8.0'
    implementation 'org.mapsforge:mapsforge-map:0.8.0'
    implementation 'org.mapsforge:mapsforge-map-android:0.8.0'
    implementation 'org.mapsforge:mapsforge-map-reader:0.8.0'
    implementation 'org.slf4j:slf4j-android:1.7.10'
    implementation 'org.slf4j:slf4j-api:1.7.10'
    implementation 'org.mapsforge:mapsforge-themes:0.8.0'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.jjoe64:graphview:4.0.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.google.android.gms:play-services-drive:15.0.1'
    implementation 'com.google.android.gms:play-services-ads:15.0.1'
    implementation 'com.google.android.gms:play-services-gcm:15.0.1'
    implementation 'com.google.android.gms:play-services-location:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:11.0.1'
    implementation 'com.google.android.gms:play-services-places:15.0.1'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'com.startapp:inapp-sdk:3.9.3'
}
`

**Comment by Starcommander** [comment]
Hello Mehrankhan.
Thanks for your report.

But can you provide a little bit more information.
What is the Version of Pocketmaps, where you got this connection problem?
Android device/version?
And all your config data has not verry much to do with Pocket Maps.

My bed is, that you have installed the old version of PocketMaps, that searches on a no more existing server.
