### ISSUE TITLE
Make it possible to change language

### ISSUE THREAD

**Issue by TimvanSteenbergen** [junjunguo/PocketMaps#94]
To Dutch in my case.
What file contains the language-information. If it is possible to change it by myself, then how can I change it by myself?

**Comment by Starcommander** [comment]
This is the file containing the text in english:
https://github.com/junjunguo/PocketMaps/blob/master/PocketMaps/app/src/main/res/values/strings.xml
The german file is in the folder values-de instead.
You can alter the file and send to my email-address soundmodul AT gmx.at

Best regards,
Paul

**Comment by Starcommander** [comment]
Thanks for your translation-support.
