### ISSUE TITLE
How does updates work?

### ISSUE THREAD

**Issue by natrius** [junjunguo/PocketMaps#95]
Some questions: 
How often does the map gets updates?
Do we get information about updates?
How can we download updates? - Do we have to delete the old one and download the new one?
Can we see the version of the map we downloaded (date would be appreciated)

**Comment by Starcommander** [comment]
All the maps were generated this year 2018.
Currently I have to trigger a rebuild manually.
I have planned to re-generate the maps once a year.
This needs a lot of resources on the server.
But yes, you will see a message for updating the map.
Then you have to enter the plus-button and select the update-symbol on your map.
Currently it is not possible to see the map-version on the app.
But you can look at the server, where the date is also listed:
http://vsrv15044.customer.xenway.de/maps/

**Comment by stephan75** [comment]
On the mentioned map server i cannot find any map file for Germany ... Or am.i blind?

Although those.map files are offered for download inside the app!

How can this happen?

**Comment by natrius** [comment]
*lol* he is correct. No germany on the mentioned homepage, in the app itself it shows up, i checked it. 

Another suggestion for naming: 
continent-country(option: -federal state)-date
So europe_germany_bavaria_2018-02.ghz for example. This way everything is correctly ordered and the date is still visible.

**Comment by Starcommander** [comment]
Ok that is correct, because some maps I created at home, not on the server.
But they are all 2018.

I will not change the name of the files, because this is a very complex task.
But I can change the order, listed on server.

Building the maps is not easy, and can fail on multiple steps, so my decision was to do this manually.
If anyone has the time to create more updates on a (more powerful?) server - be free to help.

**Comment by natrius** [comment]
Do you have a proper documentation or checklist on how to update or generate a new map? Put it in the wiki.

And, group "europe" togehter, thats the only reason i suggested putting the date to the end. That was a bit confusing at first. But actually, if its much effort, just leave it. STRG+F is working, if everything is peresent :D

**Comment by Starcommander** [comment]
Look at the "how to create maps" section of Readme.md, or use the direct link:
[https://github.com/junjunguo/PocketMaps/blob/master/documentation/create_maps.md](url)
