### ISSUE TITLE
tracking analytics - gpx-file

### ISSUE THREAD

**Issue by Cligle** [junjunguo/PocketMaps#97]
During tracking it is possible to use tracking analytics. However, once the track is saved, there is no possibility to use the option of tracking analytics. 
Would it be possible to implement an open-gpx-file-function? 
It would be great if all current analytic items (distance, activity, calories, max. speed, duration and avg. speed) could be reported and if, additionaly, the route could be displayed on a map.

**Comment by Starcommander** [comment]
Solved with commit number:
bd8a2c6f741ea9af0d799afb411778db2b781369

Now it is possible to load a gpx file, show statistics and route.
Available on next release.
