### ISSUE TITLE
[Q] What the difference from osmand~ app

### ISSUE THREAD

**Issue by jerryn70** [junjunguo/PocketMaps#98]
My country map is more than 1gb so before downloading that I want to know what is the difference between this app and osmand .

**Comment by Starcommander** [comment]
I did never try OsmAnd!
But regarding to [FDroid](https://f-droid.org/en/packages/net.osmand.plus/) the license is not completely free.
And on Google-Play is explained that OsmAnd promotes In-App-Products.
On the other side, OsmAnd is used from a lot of more people, and is possibly more tested.
Also there are a lot of more developers working on OsmAnd.
But why dont you try it out, the download is free :)
You can also use a smaller map for first tests.
Best regards.

**Comment by jerryn70** [comment]
Tested osmand bcoz it can download the state wise maps. 
Your app is in pending bcoz your app downloads only country wise maps. 

State wise size is just 50mb and my country wise map is 1gb
